// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! KLL Sketch Serialization Compatibility Tests
//!
//! These tests verify binary compatibility with Apache DataSketches implementations:
//! - Java (datasketches-java)
//! - C++ (datasketches-cpp)
//! - Go (datasketches-go)
//!
//! Test data is generated by the reference implementations and stored in:
//! `tests/serde_tests/{java_generated_files,cpp_generated_files}/`.

use std::cmp::Ordering;
use std::fs;
use std::path::PathBuf;

use datasketches::codec::SketchBytes;
use datasketches::codec::SketchSlice;
use datasketches::error::Error;
use datasketches::error::ErrorKind;
use datasketches::kll::KllFloat;
use datasketches::kll::KllSketch;
use datasketches::kll::KllValue;

use crate::serialization_test_data;

const DEFAULT_K: u16 = 200;

#[derive(Debug, Clone, PartialEq, Eq)]
struct NumericString(String);

impl Ord for NumericString {
    fn cmp(&self, other: &Self) -> Ordering {
        parse_string_value(&self.0).cmp(&parse_string_value(&other.0))
    }
}

impl PartialOrd for NumericString {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl KllValue for NumericString {
    const MIN_SERIALIZED_SIZE: usize = String::MIN_SERIALIZED_SIZE;

    fn serialized_size(value: &Self) -> usize {
        String::serialized_size(&value.0)
    }

    fn serialize(value: &Self, bytes: &mut SketchBytes) {
        String::serialize(&value.0, bytes);
    }

    fn deserialize(input: &mut SketchSlice<'_>) -> Result<Self, Error> {
        String::deserialize(input).map(Self)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
struct Record {
    key: i64,
    category: u16,
}

impl KllValue for Record {
    const MIN_SERIALIZED_SIZE: usize = 10;

    fn serialized_size(_value: &Self) -> usize {
        10
    }

    fn serialize(value: &Self, bytes: &mut SketchBytes) {
        bytes.write_i64_le(value.key);
        bytes.write_u16_le(value.category);
    }

    fn deserialize(input: &mut SketchSlice<'_>) -> Result<Self, Error> {
        let key = input
            .read_i64_le()
            .map_err(|_| Error::new(ErrorKind::InvalidData, "missing record key"))?;
        let category = input
            .read_u16_le()
            .map_err(|_| Error::new(ErrorKind::InvalidData, "missing record category"))?;
        Ok(Self { key, category })
    }
}

fn test_f32_file(path: PathBuf, expected_n: usize) {
    let bytes = fs::read(&path).unwrap();
    let sketch = KllSketch::<KllFloat<f32>>::deserialize(&bytes)
        .unwrap_or_else(|error| panic!("{}: {error}", path.display()));

    assert_eq!(sketch.k(), DEFAULT_K, "wrong k in {}", path.display());
    assert_eq!(
        sketch.n() as usize,
        expected_n,
        "wrong n in {}",
        path.display()
    );
    assert_eq!(
        sketch.is_estimation_mode(),
        expected_n > DEFAULT_K as usize,
        "wrong estimation mode in {}",
        path.display()
    );
    assert_eq!(
        sketch.is_empty(),
        expected_n == 0,
        "wrong empty flag in {}",
        path.display()
    );

    if expected_n == 0 {
        assert!(sketch.min_item().is_none(), "min should be None");
        assert!(sketch.max_item().is_none(), "max should be None");
    } else {
        assert_eq!(
            sketch.min_item().map(|value| **value),
            Some(1.0),
            "min item mismatch in {}",
            path.display()
        );
        assert_eq!(
            sketch.max_item().map(|value| **value),
            Some(expected_n as f32),
            "max item mismatch in {}",
            path.display()
        );
    }

    assert_eq!(sketch.serialize(), bytes, "roundtrip: {}", path.display());
}

fn test_f64_file(path: PathBuf, expected_n: usize) {
    let bytes = fs::read(&path).unwrap();
    let sketch = KllSketch::<KllFloat<f64>>::deserialize(&bytes)
        .unwrap_or_else(|error| panic!("{}: {error}", path.display()));

    assert_eq!(sketch.k(), DEFAULT_K, "wrong k in {}", path.display());
    assert_eq!(
        sketch.n() as usize,
        expected_n,
        "wrong n in {}",
        path.display()
    );
    assert_eq!(
        sketch.is_estimation_mode(),
        expected_n > DEFAULT_K as usize,
        "wrong estimation mode in {}",
        path.display()
    );
    assert_eq!(
        sketch.is_empty(),
        expected_n == 0,
        "wrong empty flag in {}",
        path.display()
    );

    if expected_n == 0 {
        assert!(sketch.min_item().is_none(), "min should be None");
        assert!(sketch.max_item().is_none(), "max should be None");
    } else {
        assert_eq!(
            sketch.min_item().map(|value| **value),
            Some(1.0),
            "min item mismatch in {}",
            path.display()
        );
        assert_eq!(
            sketch.max_item().map(|value| **value),
            Some(expected_n as f64),
            "max item mismatch in {}",
            path.display()
        );
    }

    assert_eq!(sketch.serialize(), bytes, "roundtrip: {}", path.display());
}

fn test_i64_file(path: PathBuf, expected_n: usize) {
    let bytes = fs::read(&path).unwrap();
    let sketch = KllSketch::<i64>::deserialize(&bytes)
        .unwrap_or_else(|error| panic!("{}: {error}", path.display()));

    assert_eq!(sketch.k(), DEFAULT_K, "wrong k in {}", path.display());
    assert_eq!(
        sketch.n() as usize,
        expected_n,
        "wrong n in {}",
        path.display()
    );
    assert_eq!(
        sketch.is_estimation_mode(),
        expected_n > DEFAULT_K as usize,
        "wrong estimation mode in {}",
        path.display()
    );
    assert_eq!(
        sketch.is_empty(),
        expected_n == 0,
        "wrong empty flag in {}",
        path.display()
    );

    if expected_n == 0 {
        assert!(sketch.min_item().is_none(), "min should be None");
        assert!(sketch.max_item().is_none(), "max should be None");
    } else {
        assert_eq!(
            sketch.min_item().cloned(),
            Some(1),
            "min item mismatch in {}",
            path.display()
        );
        assert_eq!(
            sketch.max_item().cloned(),
            Some(expected_n as i64),
            "max item mismatch in {}",
            path.display()
        );
    }

    assert_eq!(sketch.serialize(), bytes, "roundtrip: {}", path.display());
}

fn parse_string_value(value: &str) -> u64 {
    value
        .trim_start()
        .parse::<u64>()
        .expect("string value should be numeric")
}

fn test_string_file(path: PathBuf, expected_n: usize) {
    let bytes = fs::read(&path).unwrap();
    let sketch = KllSketch::<NumericString>::deserialize(&bytes)
        .unwrap_or_else(|error| panic!("{}: {error}", path.display()));

    assert_eq!(sketch.k(), DEFAULT_K, "wrong k in {}", path.display());
    assert_eq!(
        sketch.n() as usize,
        expected_n,
        "wrong n in {}",
        path.display()
    );
    assert_eq!(
        sketch.is_estimation_mode(),
        expected_n > DEFAULT_K as usize,
        "wrong estimation mode in {}",
        path.display()
    );
    assert_eq!(
        sketch.is_empty(),
        expected_n == 0,
        "wrong empty flag in {}",
        path.display()
    );

    if expected_n == 0 {
        assert!(sketch.min_item().is_none(), "min should be None");
        assert!(sketch.max_item().is_none(), "max should be None");
    } else {
        let min_item = sketch.min_item().expect("missing min item");
        let max_item = sketch.max_item().expect("missing max item");
        assert_eq!(
            parse_string_value(&min_item.0),
            1,
            "min item mismatch in {}",
            path.display()
        );
        assert_eq!(
            parse_string_value(&max_item.0),
            expected_n as u64,
            "max item mismatch in {}",
            path.display()
        );
    }

    assert_eq!(sketch.serialize(), bytes, "roundtrip: {}", path.display());
}

#[test]
fn test_java_kll_float_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];
    for n in test_cases {
        let filename = format!("kll_float_n{n}_java.sk");
        let path = serialization_test_data("java_generated_files", &filename);
        test_f32_file(path, n);
    }
}

#[test]
fn test_java_kll_double_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];
    for n in test_cases {
        let filename = format!("kll_double_n{n}_java.sk");
        let path = serialization_test_data("java_generated_files", &filename);
        test_f64_file(path, n);
    }
}

#[test]
fn test_java_kll_long_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];
    for n in test_cases {
        let filename = format!("kll_long_n{n}_java.sk");
        let path = serialization_test_data("java_generated_files", &filename);
        test_i64_file(path, n);
    }
}

#[test]
fn test_java_kll_string_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];
    for n in test_cases {
        let filename = format!("kll_string_n{n}_java.sk");
        let path = serialization_test_data("java_generated_files", &filename);
        test_string_file(path, n);
    }
}

#[test]
fn test_cpp_kll_float_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];
    for n in test_cases {
        let filename = format!("kll_float_n{n}_cpp.sk");
        let path = serialization_test_data("cpp_generated_files", &filename);
        test_f32_file(path, n);
    }
}

#[test]
fn test_cpp_kll_double_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];
    for n in test_cases {
        let filename = format!("kll_double_n{n}_cpp.sk");
        let path = serialization_test_data("cpp_generated_files", &filename);
        test_f64_file(path, n);
    }
}

#[test]
fn test_cpp_kll_long_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];
    for n in test_cases {
        let filename = format!("kll_long_n{n}_cpp.sk");
        let path = serialization_test_data("cpp_generated_files", &filename);
        test_i64_file(path, n);
    }
}

#[test]
fn test_cpp_kll_string_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];
    for n in test_cases {
        let filename = format!("kll_string_n{n}_cpp.sk");
        let path = serialization_test_data("cpp_generated_files", &filename);
        test_string_file(path, n);
    }
}

#[test]
fn test_go_kll_float_compatibility() {
    for n in [0, 1, 10, 100, 1000, 10000, 100000, 1000000] {
        let path = serialization_test_data("go_generated_files", &format!("kll_float_n{n}_go.sk"));
        test_f32_file(path, n);
    }
}

#[test]
fn test_go_kll_double_compatibility() {
    for n in [0, 1, 10, 100, 1000, 10000, 100000, 1000000] {
        let path = serialization_test_data("go_generated_files", &format!("kll_double_n{n}_go.sk"));
        test_f64_file(path, n);
    }
}

#[test]
fn test_go_kll_long_compatibility() {
    for n in [0, 1, 10, 100, 1000, 10000, 100000, 1000000] {
        let path = serialization_test_data("go_generated_files", &format!("kll_long_n{n}_go.sk"));
        test_i64_file(path, n);
    }
}

#[test]
fn test_go_kll_string_compatibility() {
    for n in [0, 1, 10, 100, 1000, 10000, 100000, 1000000] {
        let path = serialization_test_data("go_generated_files", &format!("kll_string_n{n}_go.sk"));
        test_string_file(path, n);
    }
}

#[test]
fn test_custom_kll_value_roundtrip() {
    let mut sketch = KllSketch::<Record>::new(64).unwrap();
    for key in 0..1_000 {
        sketch.update(Record {
            key,
            category: (key % 7) as u16,
        });
    }

    let decoded = KllSketch::<Record>::deserialize(&sketch.serialize()).unwrap();

    assert_eq!(decoded, sketch);
    assert_eq!(decoded.n(), 1_000);
    assert_eq!(decoded.num_retained(), sketch.num_retained());
}

#[test]
fn test_rejects_truncated_or_trailing_data() {
    let mut sketch = KllSketch::<KllFloat<f32>>::default();
    for value in 0..1_000 {
        sketch.update(KllFloat::<f32>::new(value as f32).unwrap());
    }
    let bytes = sketch.serialize();

    for length in [7, 15, bytes.len() - 1] {
        assert!(KllSketch::<KllFloat<f32>>::deserialize(&bytes[..length]).is_err());
    }

    let mut with_trailing_data = bytes;
    with_trailing_data.push(0);
    assert!(KllSketch::<KllFloat<f32>>::deserialize(&with_trailing_data).is_err());
}

#[test]
fn test_string_value_reports_the_truncated_field_and_byte_counts() {
    let mut input = SketchSlice::new(&[5, 0, 0, 0, b'a']);

    let error = String::deserialize(&mut input).unwrap_err();

    assert_eq!(error.kind(), ErrorKind::InvalidData);
    assert_eq!(
        error.message(),
        "insufficient data (KLL string payload): expected 5 bytes, got 1"
    );
}
